import { Event } from '@prisma/client'

export interface CreateEventDTO {
  title: Event['title']
  slug: Event['slug']
  description: Event['description']
  value: Event['value']
  initialDate: Event['initialDate']
  finalDate: Event['finalDate']
  status: Event['status']
  visible: Event['visible']
  departmentId: Event['departmentId']
  eventType: Event['eventType']
  imagePath: Event['imagePath']
  street?: Event['street']
  number?: Event['number']
  complement?: Event['complement']
  neighborhood?: Event['neighborhood']
  state?: Event['state']
  city?: Event['city']
  latitude?: Event['latitude']
  longitude?: Event['longitude']
  message?: Event['message']
  createdBy: Event['createdBy']
}
